# 指定应用程序端口
server:
 port: 8001

# SpringBoot 整合 MyBatis  
mybatis:
 config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
 type-aliases-package: com.pengguozhen.springcloud.entities    # 所有Entity别名类所在包
 mapper-locations:
 - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

# SpringBoot 整合 Spring    
spring:
 application:
  name: microservicecloud-dept                             # 微服务应用对外暴露的name
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
  driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
  url: jdbc:mysql://localhost:3306/clouddb01              # 数据库名称
  username: root
  password: root
  dbcp2:
   min-idle: 5                                           # 数据库连接池的最小维持连接数
   initial-size: 5                                       # 初始化连接数
   max-total: 5                                          # 最大连接数
   max-wait-millis: 200 # 等待连接获取的最大超时时间

# 指定服务注册中心
eureka:
 client:
  service-url:
   defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
 instance:
  instance-id: microservicecloud-dept8001 # 设置注册到服务中心时的服务名
  prefer-ip-address: true # 访问路径可以显示 IP

info:
 app.name: pengguozhen-microservicecloud
 company.name: Ta 的笑很甜
 build.artifactId: $project.artifactId$
 build.version: $project.version$
